---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: 8-demo-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: 8-demo
    commit:
      author:
        email: flffl@gmail.com
        name: nezih-robot
    push:
      branch: 8-demo
  interval: 10s
  sourceRef:
    kind: GitRepository
    name: 8-demo-source
  update:
    path: ./manifest
    strategy: Setters
