---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: 8-demo-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: 8-demo-repo
  policy:
    semver:
      range: 7.8.x
