---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 3-demo-kustomize
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: 3-demo-source
  targetNamespace: 3-demo--path
