---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: 5-demo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo
  interval: 10s
  targetNamespace: 5-demo
  values:
    fullnameOverride: ""
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.5.0
      tag: ""
    imagePullSecrets: []
    labels:
      app:
        env: uat
        name: bb-app
        version: 7.5.0
    nameOverride: ""
    namespace:
      name: 5-demo
    replicaCount: 1
    service:
      port: 80
      targetPort: 80
      type: LoadBalancer
